#:schema https://dystroy.org/bacon/.bacon.schema.json

# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "wasm"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

[jobs.wasm]
command = ["wasm-pack", "build", "--target", "web"]
need_stdout = true
allow_warnings = true
